#!/bin/sh

ps aux | grep ardupilot | awk '{print $2}' | xargs kill
ps aux | grep mavproxy | awk '{print $2}' | xargs kill

for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
do
	sleep 2
	gnome-terminal --title=MavProxy$i --geometry=90x30 --hide-menubar -x sh -c "cd ardupilot32/ArduCopter && sim_vehicle.sh -I$i -L Lab --aircraft test --quadcopter ;bash"
done

#gnome-terminal --title=MavProxy --geometry=90x30 --hide-menubar -x sh -c "cd ardupilot32/ArduCopter && sim_vehicle.sh -I2 -L Lab --console --map --aircraft test --quadcopter ;bash"

